/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testgraphics;

import java.awt.*;
import javax.swing.*;

/**
 * @author yaelanaya
 */
public class DataDialog extends javax.swing.JDialog {

    private Color color; //Color de la figura.
    private static boolean isSpiralSelected; //indica si se sleccionó la Espiral.
    
    public DataDialog(java.awt.Frame parent, boolean modal, boolean spiralState) {
        super(parent, modal);
        initComponents();
        isSpiralSelected = spiralState;
        //Con este método sabremos si se clikeo la espiral.
        isSpiral(spiralState);
    }

    /**
     * Con los métodos Getters retornamos los valores introducidos por el usuario
     * , estos valores se convierten a enteros mediante el método convertToInteger.
     */
    public int getFigureIncrement() {
        return convertTextToInteger(incrementTextField);
    }

    public int getFigureRadium() {
        return convertTextToInteger(radiusTextField);
    }

    public int getFigureSize() {
        return convertTextToInteger(sizeTextField);
    }

    public int getXPosition() {
        return convertTextToInteger(xPositionTextField);
    }

    public int getYPosition() {
        return convertTextToInteger(yPositionTextField);
    }
   
    //Retornamos el color elegido por el usuario  mediante el JcolorChoosen.
    public Color getColor() {
        return color;
    }
    
    
    /**
     * Con este método cambiamos el tamaño de la ventana de diálogo cada que se pique el 
     * botón de la espiral, también mostraremos los campos para llenar de la Espiral.
     */
    private void isSpiral(boolean isSpiralSelected) {
        if (isSpiralSelected) {
            setBounds(new Rectangle(1120, 450, 215, 260));   
            incrementLabel.setVisible(isSpiralSelected);
            incrementTextField.setVisible(isSpiralSelected);
            radiusLabel.setVisible(isSpiralSelected);
            radiusTextField.setVisible(isSpiralSelected);
        }
    }
    /**
     * Este método valida que no se ingresó un espacio en blanco o caracteres que no sean
     * numéricos; si no hay un espacio en blanco y se ingresó un número, se convertirá el
     * String a entero y retornará el resultado de la conversión, en caso contrario, el método
     * retorna un 0.
     * @param text Objeto JTextField del que obtenemos el String.
     */
    private int convertTextToInteger(JTextField text){
        if (!text.getText().isBlank() && text.getText().chars().allMatch(Character::isDigit) && !text.getText().startsWith("-")) {
            return Integer.parseInt(text.getText());
        }
        return 0;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agreeButton = new javax.swing.JButton();
        ColorButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        xPositionLabel = new javax.swing.JLabel();
        xPositionTextField = new javax.swing.JTextField();
        yPositionLabel = new javax.swing.JLabel();
        yPositionTextField = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        radiusLabel = new javax.swing.JLabel();
        radiusTextField = new javax.swing.JTextField();
        incrementLabel = new javax.swing.JLabel();
        incrementTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new Rectangle(800, 300, 250, 260));
        setLocation(new java.awt.Point(1120, 450));
        setMinimumSize(new java.awt.Dimension(220, 135));
        setName("Datos de la Figura"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(250, 20));

        agreeButton.setText("Aceptar");
        agreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(agreeButton);

        ColorButton.setText("Color");
        ColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ColorButton);

        jPanel2.setAlignmentY(0.4F);
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 6, 6);
        flowLayout2.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout2);

        xPositionLabel.setText("Posición en [X]:");
        xPositionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(xPositionLabel);

        xPositionTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        xPositionTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(xPositionTextField);

        yPositionLabel.setText("Posición en [Y]:");
        yPositionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(yPositionLabel);

        yPositionTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        yPositionTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(yPositionTextField);

        sizeLabel.setText("Tamaño:");
        sizeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(sizeLabel);

        sizeTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        sizeTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(sizeTextField);

        radiusLabel.setText("Radio inical:");
        radiusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(radiusLabel);

        radiusTextField.setMinimumSize(new java.awt.Dimension(86, 26));
        radiusTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(radiusTextField);

        incrementLabel.setText("Incremento:");
        incrementLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(incrementLabel);

        incrementTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        incrementTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(incrementTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Cada que se pique el botón, se despliega el color choosher.
    private void ColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorButtonActionPerformed
        color = JColorChooser.showDialog(this, "Seleccione el color de su figura", color.BLACK);
    }//GEN-LAST:event_ColorButtonActionPerformed
    
    //Cuando se usa el botón de aceptar, se cierra la ventana.
    private void agreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_agreeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DataDialog dialog;
                dialog = new DataDialog(new javax.swing.JFrame(), false, isSpiralSelected);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColorButton;
    private javax.swing.JButton agreeButton;
    private javax.swing.JLabel incrementLabel;
    private javax.swing.JTextField incrementTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel radiusLabel;
    private javax.swing.JTextField radiusTextField;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JLabel xPositionLabel;
    private javax.swing.JTextField xPositionTextField;
    private javax.swing.JLabel yPositionLabel;
    private javax.swing.JTextField yPositionTextField;
    // End of variables declaration//GEN-END:variables
}
