/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testgraphics;

import java.awt.*;
import javax.swing.*;

/**
 *
 * @author yaelanaya
 */
public class DataDialog extends javax.swing.JDialog {

    private Color color;
    
    public DataDialog(java.awt.Frame parent, boolean modal, boolean isSpiralSelected) {
        super(parent, modal);
        initComponents();
        
        isSpiral(isSpiralSelected);
    }

    private DataDialog(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public int getIncrementTextField() {
        if (!incrementTextField.getText().isBlank()
            && incrementTextField.getText().chars().allMatch(Character::isDigit)) {
            return Integer.parseInt(incrementTextField.getText());
        }

        return 0;
    }

    public int getRadiumTextField() {
        if (!radiumTextField.getText().isBlank()
            && radiumTextField.getText().chars().allMatch(Character::isDigit)) {
            return Integer.parseInt(radiumTextField.getText());
        }

        return 0;
    }

    public int getSizeTextField() {
        if (!sizeTextField.getText().isBlank()
             && sizeTextField.getText().chars().allMatch(Character::isDigit)) {
            return Integer.parseInt(sizeTextField.getText());
        }
        return 0;
    }

    public int getxPositionTextField() {
        if (!xPositionTextField.getText().isBlank()
            && xPositionTextField.getText().chars().allMatch(Character::isDigit)) {
            return Integer.parseInt(xPositionTextField.getText());
        }
        return 0;
    }

    public int getyPositionTextField() {
        if (!yPositionTextField.getText().isBlank()
            && yPositionTextField.getText().chars().allMatch(Character::isDigit)) {
            return Integer.parseInt(yPositionTextField.getText());
        }
        return 0;
    }

    private void isSpiral(boolean isSpiralSelected) {
        if (isSpiralSelected) {
            setBounds(new Rectangle(1120, 450, 215, 260));
        }

        incrementLabel.setVisible(isSpiralSelected);
        incrementTextField.setVisible(isSpiralSelected);
        radiumLabel.setVisible(isSpiralSelected);
        radiumTextField.setVisible(isSpiralSelected);

    }

    public Color getColor() {
        return color;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agreeButton = new javax.swing.JButton();
        ColorButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        xPositionLabel = new javax.swing.JLabel();
        xPositionTextField = new javax.swing.JTextField();
        yPositionLabel = new javax.swing.JLabel();
        yPositionTextField = new javax.swing.JTextField();
        sizeLabel = new javax.swing.JLabel();
        sizeTextField = new javax.swing.JTextField();
        radiumLabel = new javax.swing.JLabel();
        radiumTextField = new javax.swing.JTextField();
        incrementLabel = new javax.swing.JLabel();
        incrementTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new Rectangle(800, 300, 250, 260));
        setLocation(new java.awt.Point(1120, 450));
        setMinimumSize(new java.awt.Dimension(220, 135));
        setName("Datos de la Figura"); // NOI18N
        setPreferredSize(new java.awt.Dimension(220, 195));
        setResizable(false);
        setSize(new java.awt.Dimension(250, 20));

        agreeButton.setText("Aceptar");
        agreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(agreeButton);

        ColorButton.setText("Color");
        ColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ColorButton);

        jPanel2.setAlignmentY(0.4F);
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING, 6, 6);
        flowLayout2.setAlignOnBaseline(true);
        jPanel2.setLayout(flowLayout2);

        xPositionLabel.setText("Posición en [X]:");
        xPositionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(xPositionLabel);

        xPositionTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        xPositionTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        xPositionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xPositionTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(xPositionTextField);

        yPositionLabel.setText("Posición en [Y]:");
        yPositionLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(yPositionLabel);

        yPositionTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        yPositionTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(yPositionTextField);

        sizeLabel.setText("Tamaño:");
        sizeLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(sizeLabel);

        sizeTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        sizeTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        sizeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeTextFieldActionPerformed(evt);
            }
        });
        jPanel2.add(sizeTextField);

        radiumLabel.setText("Radio inical:");
        radiumLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(radiumLabel);

        radiumTextField.setMinimumSize(new java.awt.Dimension(86, 26));
        radiumTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(radiumTextField);

        incrementLabel.setText("Incremento:");
        incrementLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel2.add(incrementLabel);

        incrementTextField.setMinimumSize(new java.awt.Dimension(86, 21));
        incrementTextField.setPreferredSize(new java.awt.Dimension(86, 26));
        jPanel2.add(incrementTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xPositionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xPositionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xPositionTextFieldActionPerformed

    private void sizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sizeTextFieldActionPerformed

    private void ColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorButtonActionPerformed
        // TODO add your handling code here:
        color = JColorChooser.showDialog(this, "Seleccione el color de su figura", color.BLACK);
    }//GEN-LAST:event_ColorButtonActionPerformed

    private void agreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_agreeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DataDialog dialog;
                dialog = new DataDialog(new javax.swing.JFrame(), false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ColorButton;
    private javax.swing.JButton agreeButton;
    private javax.swing.JLabel incrementLabel;
    private javax.swing.JTextField incrementTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel radiumLabel;
    private javax.swing.JTextField radiumTextField;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JTextField sizeTextField;
    private javax.swing.JLabel xPositionLabel;
    private javax.swing.JTextField xPositionTextField;
    private javax.swing.JLabel yPositionLabel;
    private javax.swing.JTextField yPositionTextField;
    // End of variables declaration//GEN-END:variables
}
